"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const BedRoom_1 = require("./BedRoom");
const Home_1 = require("./Home");
const Kitchen_1 = require("./Kitchen");
const LivingRoom_1 = require("./LivingRoom");
const Wc_1 = require("./Wc");
const cuisine = new Kitchen_1.Kitchen("cuisine", 13, 12, false);
const chambre = new BedRoom_1.BedRoom("chambre", 13, 12, true);
const salon = new LivingRoom_1.LivingRoom("salon", 30, 10, true);
const salon1 = new LivingRoom_1.LivingRoom("salon1", 30, 10, true);
const douche = new BedRoom_1.BedRoom("douche", 20, 10, false);
const wc = new Wc_1.Wc("toillet1", 10, 20, false);
const wc2 = new Wc_1.Wc("toillet2", 10, 20, false);
const home = new Home_1.Home();
home.addRoom(cuisine);
home.addRoom(chambre);
home.addRoom(salon);
home.addRoom(salon1);
home.addRoom(wc);
home.addRoom(wc2);
home.addRoom(douche);
console.log(home);
